
"use client";
import Link from "next/link";import{useState}from"react";import{api}from"../lib/api";
const cards=[["01","Find Colleges","Stop doom-scrolling. Build your shortlist.","/colleges","↗"],["02","AI Search","Type what you mean. AI does the sorting.","/ai-search","✦"],["03","Predictor","Rank/score in. Realistic shortlist out.","/predictor","◎"],["04","Scholarships","Money-saving mode: ON.","/scholarships","₹"],["05","Mock Tests","Practice. Panic less. Repeat.","/mock-tests","⚡"],["06","Get Help","A human counsellor when you need one.","#help","♡"]];
export default function Home(){const[q,setQ]=useState("");const[r,setR]=useState<any>();async function search(e:any){e.preventDefault();if(!q.trim())return;try{setR(await api("/api/v1/ai/search",{method:"POST",body:JSON.stringify({question:q})}))}catch(e:any){setR({answer:e.message})}}
return <div>
<section className="hero-gradient text-white overflow-hidden"><div className="container py-20 md:py-28 relative"><div className="absolute right-0 top-14 text-[100px] md:text-[170px] font-black opacity-10 select-none">GO!</div><span className="inline-flex bg-white/10 border border-white/20 rounded-full px-4 py-2 text-sm font-bold">✦ education, but make it less boring</span><h1 className="text-5xl md:text-7xl font-black leading-[.95] tracking-tight max-w-5xl mt-7">Your next chapter<br/><span className="text-lime-300">starts here.</span></h1><p className="text-lg md:text-xl text-slate-200 max-w-2xl mt-7">Colleges. Courses. Scholarships. Exams. AI. Human help. One place to figure out what comes next.</p>
<form onSubmit={search} className="mt-9 max-w-4xl bg-white p-2 rounded-2xl flex flex-col md:flex-row gap-2 shadow-2xl"><input className="input border-0 text-slate-900 text-lg" value={q} onChange={e=>setQ(e.target.value)} placeholder='Try “private BHMS colleges in Karnataka with hostel”'/><button className="btn btn-electric">Search with AI ✦</button></form>
<div className="mt-5 flex flex-wrap gap-2 text-sm"><span className="bg-white/10 px-3 py-2 rounded-full">BHMS</span><span className="bg-white/10 px-3 py-2 rounded-full">BAMS</span><span className="bg-white/10 px-3 py-2 rounded-full">Nursing</span><span className="bg-white/10 px-3 py-2 rounded-full">B.Pharm</span><span className="bg-white/10 px-3 py-2 rounded-full">MBA</span></div>
{r&&<div className="card text-slate-900 mt-6 max-w-4xl"><b className="text-violet-700">AI says</b><p className="mt-2 whitespace-pre-wrap">{r.answer}</p></div>}</div></section>
<div className="bg-lime-300 text-slate-900 py-3 font-black marquee"><span>FIND YOUR FIT ✦ COMPARE SMARTER ✦ SAVE MONEY ✦ ASK AI ✦ GET HUMAN HELP ✦ FIND YOUR FIT ✦ COMPARE SMARTER ✦ SAVE MONEY ✦ ASK AI ✦</span></div>
<section className="container py-16"><div className="flex justify-between gap-5 items-end"><div><span className="badge">THE TOOLKIT</span><h2 className="text-4xl md:text-5xl font-black mt-3">Pick your move.</h2></div><Link href="/colleges" className="hidden md:block font-black text-violet-700">See everything →</Link></div>
<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-9">{cards.map(([n,t,d,u,icon])=><Link key={t} href={u} className="card group hover:-translate-y-2 transition-all duration-300 relative overflow-hidden"><div className="flex justify-between"><span className="text-xs font-black text-slate-400">{n}</span><span className="text-3xl floaty">{icon}</span></div><h3 className="text-2xl font-black mt-8">{t}</h3><p className="text-slate-500 mt-2">{d}</p><div className="mt-7 font-black text-violet-700">Open →</div></Link>)}</div></section>
<section id="help" className="container pb-16"><div className="card hero-gradient text-white p-8 md:p-12"><div className="grid md:grid-cols-[1fr_auto] gap-8 items-center"><div><span className="badge bg-white text-violet-700">NO JUDGEMENT ZONE</span><h2 className="text-4xl md:text-5xl font-black mt-4">Confused is allowed.</h2><p className="text-slate-200 mt-3 max-w-2xl">Tell Padhaanewala what you're trying to study and where. Submit an enquiry and a counsellor can help you work through the options.</p></div><Link href="/#enquiry" className="btn btn-electric">Talk to a counsellor →</Link></div></div></section>
<section id="enquiry" className="bg-white border-t py-16"><div className="container max-w-3xl"><Enquiry/></div></section></div>}
function Enquiry(){const[f,setF]=useState({name:"",mobile:"",email:"",course:"",message:""});const[msg,setMsg]=useState("");async function go(e:any){e.preventDefault();try{const r=await api<any>("/api/v1/enquiries",{method:"POST",body:JSON.stringify(f)});setMsg(r.message)}catch(e:any){setMsg(e.message)}}return <div><span className="badge">ADMISSION HELP</span><h2 className="text-4xl font-black mt-3">Let's figure it out.</h2><form onSubmit={go} className="grid md:grid-cols-2 gap-4 mt-7">{["name","mobile","email","course"].map(k=><input key={k} className="input" required={k==="name"||k==="mobile"} placeholder={k.toUpperCase()} value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<textarea className="input md:col-span-2 min-h-28" placeholder="What's on your mind?" value={f.message} onChange={e=>setF({...f,message:e.target.value})}/><button className="btn btn-primary md:col-span-2">Send it →</button></form>{msg&&<p className="mt-4 font-bold text-violet-700">{msg}</p>}</div>}
